### PR TITLE
Use HTTP.jl for TAP queries (including uploads)

### PR DESCRIPTION
**Pull request by david-macmahon**
This implements all TAP queries using HTTP.jl rather than `download` (non-uploading queries) or `curl` (uploading queries).  This avoids problems caused by different quote handling behavior seen in different `curl` versions.  It also avoids the need to rely on external programs (e.g. curl), at least for TAP queries.  Other parts of this package still using curl may be able to benefit similarly from using HTTP.jl.

Users can specify additional keyword arguments for `HTTP.request` by putting them in `VirtualObservatory.HTTP_REQUEST_OPTIONS`.

### CODE REVIEW

**Comment by aplavin** [comment]
Thanks for implementing this! Not sure I fully understand the `votios2close` story, why it's needed at all?

**Comment by david-macmahon** [comment]
The user tables are written to files and then these files are re-opened to get an `IOStream` object to pass to the Http.Multipart object that is part of the form data that gets sent in the request.  These streams are not closed by HTTP.jl so we need to close them after the request is completed so that the `julia` process does not leak file descriptors (as verified by printing `vot_file` and seeing it still open via `lsof` after the request without explicitly closing it).  I suppose we could write the user tables to `IOBuffer`s instead, but then user tables would be limited to what fits in memory (which they pretty much are anyway since they originate from in-memory objects AFAICT).

**Comment by aplavin** [comment]
Looking at HTTP.jl, seems like they write the full "form" content into an in-memory IOBuffer anyways, at https://github.com/JuliaWeb/HTTP.jl/blob/b7f5aa8ede99db7139bdbbe6e430c6420c0d8795/src/multipart.jl#L124. This means the uploaded table must comfortably fit into memory in several copies. I think that should be fine, don't think many services allow huge table uploads :)
Also, I think we can just avoid any temporary files and use IOBuffers here as well... There'll just be an extra copy from "our" IOBuffer to the one in `HTTP.Form` then.

**Comment by aplavin** [comment]
Hmm, I think the NED upload test failure is a real one:
```
  Expression: execute(TAPService(:ned), "select * from TAP_UPLOAD.my"; upload = (my = mytbl,))
    Expected: "Uploads are not allowed"
     Message: "HTTP.Exceptions.StatusError(400, \"POST\", \"/tap/sync\", HTTP.Messages.Response:\n\"\"\"\nHTTP/1.1 400 Bad Request\r\nDate: Thu, 21 Nov 2024 14:22:17 GMT\r\nServer: Poseidon\r\nContent-Type: application/xml;charset=UTF-8\r\nCache-Control: public, max-age=64000\r\nExpires: Thu, 21 Nov 2024 14:22:17 GMT\r\nConnection: close\r\nTransfer-Encoding: chunked\r\n\r\n[Message Body was streamed]\"\"\")"
```
I wonder if we can somehow keep the understandable error message (that includes "Uploads are not allowed")? Otherwise the HTTP 400 error could be confusing for the user: is there a bug or what?

**Comment by david-macmahon** [comment]
`HTTP.request` is streaming the response body to `path`.  In the "ned upload" case, this is an XML document that contains:
```
<?xml version="1.0" encoding="utf-8"?>
<VOTABLE version="1.3" xmlns="http://www.ivoa.net/xml/VOTable/v1.3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.ivoa.net/xml/VOTable/v1.3 http://www.ivoa.net/xml/VOTable/v1.3">
<RESOURCE type="results">
<INFO name="QUERY_STATUS" value="ERROR">Uploads are not allowed by this service!</INFO>
<INFO name="PROVIDER" value="NASA/IPAC Extragalatic Database (NED)">NED VO Table Access Protocol (TAP) Service</INFO>
<INFO  name="REQ_ID" value="S1732211486591"/>
<INFO  name="ERROR_TYPE" value="fatal"/>
<INFO  name="ACTION" value="sync"/>
</RESOURCE>
</VOTABLE>
```
I'll have to check what the curl version does in this case, but perhaps it just returns error status and writes that XML document to `path`.  I think the thing to do is to read the body text from `path` and include that in the thrown exception whenever the status code is not 200 (or `>=300`?) .  It would probably be better to check the response status ourselves (by passing `status_exception=false` to `HTTP.request`) and throw an exception as necessary.  Any preference for what Exception type to throw?  Just `error(read("path",String))`?

**Comment by aplavin** [comment]
Included this PR with minor updates :)
HTTP exceptions are not thrown now, just logged. The actual exceptions are thrown later by VOTables, no special care needed.

**Pull request merged**
